#!/bin/bash
# setup-wifi-manager.sh — run once on the Pi to install the WiFi manager system
# Usage: bash ~/epaper-home-display/scripts/setup-wifi-manager.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_TAG="epaper-setup-wifi"

log()  { echo "[INFO]  $*"; }
warn() { echo "[WARN]  $*"; }
die()  { echo "[ERROR] $*" >&2; exit 1; }

log "=== ePaper WiFi Manager Setup ==="
log "Repo: $REPO_DIR"

# ── 1. 腳本執行權限 ────────────────────────────────────────────────────────────
log "Setting execute permission on wifi_manager.sh..."
chmod +x "$REPO_DIR/scripts/wifi_manager.sh"

# ── 2. Sudoers ─────────────────────────────────────────────────────────────────
log "Installing sudoers rules..."

SUDOERS_FILE="/etc/sudoers.d/epaper-wifi"
NMCLI=$(command -v nmcli) || die "nmcli not found — is NetworkManager installed?"

sudo tee "$SUDOERS_FILE" > /dev/null << EOF
# ePaper Home Display — WiFi provisioning (generated by setup-wifi-manager.sh)
pi ALL=(ALL) NOPASSWD: ${NMCLI} -t -f * dev wifi list --rescan no
pi ALL=(ALL) NOPASSWD: ${NMCLI} -t -f * dev wifi list --rescan auto
pi ALL=(ALL) NOPASSWD: ${NMCLI} dev wifi hotspot ifname wlan0 ssid * password *
pi ALL=(ALL) NOPASSWD: ${NMCLI} connection add type wifi *
pi ALL=(ALL) NOPASSWD: ${NMCLI} connection up EpaperWifiSetup
pi ALL=(ALL) NOPASSWD: ${NMCLI} connection delete EpaperHotspot
pi ALL=(ALL) NOPASSWD: ${NMCLI} connection delete EpaperWifiSetup
EOF

sudo chmod 440 "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" || die "sudoers syntax check failed — aborting"
log "Sudoers installed: $SUDOERS_FILE"

# ── 3. Systemd 服務 ────────────────────────────────────────────────────────────
log "Installing systemd services..."

sudo cp "$REPO_DIR/systemd/epaper-wifi-check.service"   /etc/systemd/system/
sudo cp "$REPO_DIR/systemd/epaper-home-display.service" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable epaper-wifi-check.service
log "Service enabled: epaper-wifi-check.service"

# ── 4. 重啟主服務 ──────────────────────────────────────────────────────────────
log "Restarting epaper-home-display.service..."
sudo systemctl restart epaper-home-display.service

# ── 5. 確認狀態 ────────────────────────────────────────────────────────────────
echo ""
log "=== Service Status ==="
systemctl is-active --quiet epaper-wifi-check.service \
    && log "epaper-wifi-check  : active" \
    || warn "epaper-wifi-check  : inactive (run 'sudo systemctl status epaper-wifi-check.service' to debug)"
systemctl is-active --quiet epaper-home-display.service \
    && log "epaper-home-display: active" \
    || warn "epaper-home-display: inactive (run 'sudo systemctl status epaper-home-display.service' to debug)"

echo ""
log "=== Quick Test (optional) ==="
log "Simulate AP mode:  echo '{\"mode\":\"ap\",\"ssid\":\"EpaperSetup\",\"password\":\"epaper123\",\"ip\":\"10.42.0.1\"}' | sudo tee /tmp/epaper-ap-mode.json"
log "Clear AP mode:     sudo rm /tmp/epaper-ap-mode.json"
echo ""
log "Setup complete."
