# Auto-generated by setup-windows.ps1 -- do not edit by hand; re-run setup to regenerate.
$nodeExe   = "C:\Program Files\nodejs\node.exe"
$distEntry = "F:\WorkSpace\epaper-home-display\tools\ai-usage-collector\dist\index.js"
$logFile   = "F:\WorkSpace\epaper-home-display\tools\ai-usage-collector\logs\collector.log"

if (-not (Test-Path (Split-Path $logFile))) {
    New-Item -ItemType Directory -Force (Split-Path $logFile) | Out-Null
}

& $nodeExe $distEntry *>> $logFile
